## Prep, top 1
# in /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/PhyloAcc

mkdir input_data 
cd input_data
cp /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/Comparative-Annotation-Toolkit/4d_sites/galloTop1.named.mod .
cp /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/Comparative-Annotation-Toolkit/4d_sites/galloTop2.named.mod .
cp /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/Comparative-Annotation-Toolkit/4d_sites/galloTop3.named.mod .
cp /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/alignments/aligned/galloseq.part.bed .
cp /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/alignments/aligned/galloseq_gapFixed.fa .
cd ..

# will run batches of 2000 elements each

# set up batch files
mkdir -p top1_batches
# get number of elements 
wc -l input_data/galloseq.part.bed
# shuffle lines in random order with 0-n-1 from wc -l above
shuf -i 0-356467 > top1_batches/full_list 
# make input files
split -d -a 3 -l 2000 top1_batches/full_list top1_batches/batch

# set up parameter and output files
mkdir -p top1_param
mkdir -p top1_outs

for I in $(seq 0 178); # number of batches generated by line 22
do
  printf -v BATCH "%03d" $I
  PARTFILE=top1_batches/batch$BATCH
  PREFIX=batch${BATCH}
  cat > top1_param/run$I <<EOF 
PHYTREE_FILE /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/4d_sites/galloTop1.named.mod
SEG_FILE /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/alignments/aligned/galloseq.part.bed
ALIGN_FILE /n/holyscratch01/informatics/swuitchik/ducks_project/post_cactus/cnees/alignments/aligned/galloseq_gapFixed.fa
RESULT_FOLDER top1_outs
PREFIX $PREFIX
ID_FILE $PARTFILE
CHAIN 1
BURNIN 1000
MCMC 4000
CONSERVE_PRIOR_A 5
CONSERVE_PRIOR_B 0.04
ACCE_PRIOR_A 10
ACCE_PRIOR_B 0.2
HYPER_GRATE_A 3
HYPER_GRATE_B 1
TARGETSPECIES hetAtr
CONSERVE netAur;stiNae;oxyJam;anaPla;braCan;ansInd;ansCyg;ansBra;numMel;colVir;tymCupPin;syrMik;galGal;cotJap
GAPCHAR -
NUM_THREAD 8
VERBOSE 0
CONSTOMIS 0.01
GAP_PROP 0.8
TRIM_GAP_PERCENT 0.8
EOF
done

